# Generated by Django 5.2.7 on 2025-10-24 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('license_number', models.CharField(blank=True, max_length=64)),
                ('vehicle_brand', models.CharField(blank=True, max_length=64)),
                ('vehicle_model', models.CharField(blank=True, max_length=64)),
                ('vehicle_plate', models.CharField(blank=True, max_length=32)),
                ('availability_status', models.BooleanField(blank=True, default=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unspecified', 'Unspecified')], default='Unspecified', max_length=12)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('smoking_status', models.CharField(blank=True, choices=[('allowed', 'Allowed'), ('not_allowed', 'Not Allowed'), ('unspecified', 'Unspecified')], default='Unspecified', max_length=20)),
                ('is_verified', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
