# Generated by Django 5.2.7 on 2025-10-24 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_n_service', '0003_alter_payment_date_delete_review'),
        ('core', '0001_initial'),
        ('support_n_notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favdriver',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='favdriver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_n_service.bookingdriverside')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='FavDriver',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
