# Generated by Django 5.2.7 on 2025-10-24 08:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_n_service', '0004_alter_payment_date'),
        ('support_n_notification', '0002_remove_favdriver_driver_remove_favdriver_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_n_service.bookinguserside'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 24, 14, 13, 32, 433499)),
        ),
    ]
