# Generated by Django 5.2.7 on 2025-10-24 01:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_n_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdriverside',
            name='collected_fare',
        ),
        migrations.RemoveField(
            model_name='bookinguserside',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking_user_side',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_n_service.bookinguserside'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 24, 7, 29, 44, 365946)),
        ),
    ]
