# Generated by Django 5.2.7 on 2025-10-24 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_n_service', '0002_remove_bookingdriverside_collected_fare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 24, 13, 36, 41, 898450)),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
