# Generated by Django 5.2.7 on 2025-10-24 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_n_service', '0003_alter_payment_date_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 24, 14, 13, 32, 430852)),
        ),
    ]
